#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA12F416AA37F3BD7 (dev@i-scream.org)
#
Name     : libstatgrab
Version  : 0.92.1
Release  : 2
URL      : https://github.com/libstatgrab/libstatgrab/releases/download/LIBSTATGRAB_0_92_1/libstatgrab-0.92.1.tar.gz
Source0  : https://github.com/libstatgrab/libstatgrab/releases/download/LIBSTATGRAB_0_92_1/libstatgrab-0.92.1.tar.gz
Source1  : https://github.com/libstatgrab/libstatgrab/releases/download/LIBSTATGRAB_0_92_1/libstatgrab-0.92.1.tar.gz.asc
Summary  : Provides a useful interface to system statistics
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: libstatgrab-bin = %{version}-%{release}
Requires: libstatgrab-lib = %{version}-%{release}
Requires: libstatgrab-license = %{version}-%{release}
Requires: libstatgrab-man = %{version}-%{release}
BuildRequires : grep
BuildRequires : sed

%description
https://libstatgrab.org/
Description
-----------
libstatgrab is a library for accessing information from the system
for statistical purposes. It could be used for software that monitors
the system for alerting or graphing purposes.

%package bin
Summary: bin components for the libstatgrab package.
Group: Binaries
Requires: libstatgrab-license = %{version}-%{release}

%description bin
bin components for the libstatgrab package.


%package dev
Summary: dev components for the libstatgrab package.
Group: Development
Requires: libstatgrab-lib = %{version}-%{release}
Requires: libstatgrab-bin = %{version}-%{release}
Provides: libstatgrab-devel = %{version}-%{release}
Requires: libstatgrab = %{version}-%{release}

%description dev
dev components for the libstatgrab package.


%package doc
Summary: doc components for the libstatgrab package.
Group: Documentation
Requires: libstatgrab-man = %{version}-%{release}

%description doc
doc components for the libstatgrab package.


%package lib
Summary: lib components for the libstatgrab package.
Group: Libraries
Requires: libstatgrab-license = %{version}-%{release}

%description lib
lib components for the libstatgrab package.


%package license
Summary: license components for the libstatgrab package.
Group: Default

%description license
license components for the libstatgrab package.


%package man
Summary: man components for the libstatgrab package.
Group: Default

%description man
man components for the libstatgrab package.


%prep
%setup -q -n libstatgrab-0.92.1
cd %{_builddir}/libstatgrab-0.92.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663618180
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1663618180
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libstatgrab
cp %{_builddir}/libstatgrab-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libstatgrab/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/libstatgrab-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libstatgrab/01a6b4bf79aca9b556822601186afab86e8c4fbf
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/statgrab
/usr/bin/statgrab-make-mrtg-config
/usr/bin/statgrab-make-mrtg-index

%files dev
%defattr(-,root,root,-)
/usr/include/statgrab.h
/usr/lib64/libstatgrab.so
/usr/lib64/pkgconfig/libstatgrab.pc
/usr/share/man/man3/libstatgrab.3
/usr/share/man/man3/sg_clear_error.3
/usr/share/man/man3/sg_comp_destroy.3
/usr/share/man/man3/sg_comp_get_tls.3
/usr/share/man/man3/sg_comp_init.3
/usr/share/man/man3/sg_disk_io_compare_name.3
/usr/share/man/man3/sg_disk_io_compare_traffic.3
/usr/share/man/man3/sg_drop_privileges.3
/usr/share/man/man3/sg_free_cpu_stats.3
/usr/share/man/man3/sg_free_disk_io_stats.3
/usr/share/man/man3/sg_free_fs_stats.3
/usr/share/man/man3/sg_free_host_info.3
/usr/share/man/man3/sg_free_load_stats.3
/usr/share/man/man3/sg_free_mem_stats.3
/usr/share/man/man3/sg_free_network_iface_stats.3
/usr/share/man/man3/sg_free_network_io_stats.3
/usr/share/man/man3/sg_free_page_stats.3
/usr/share/man/man3/sg_free_process_count.3
/usr/share/man/man3/sg_free_stats_buf.3
/usr/share/man/man3/sg_free_swap_stats.3
/usr/share/man/man3/sg_free_user_stats.3
/usr/share/man/man3/sg_fs_compare_device_name.3
/usr/share/man/man3/sg_fs_compare_mnt_point.3
/usr/share/man/man3/sg_get_cpu_percents.3
/usr/share/man/man3/sg_get_cpu_percents_of.3
/usr/share/man/man3/sg_get_cpu_percents_r.3
/usr/share/man/man3/sg_get_cpu_stats.3
/usr/share/man/man3/sg_get_cpu_stats_diff.3
/usr/share/man/man3/sg_get_cpu_stats_diff_between.3
/usr/share/man/man3/sg_get_cpu_stats_r.3
/usr/share/man/man3/sg_get_disk_io_stats.3
/usr/share/man/man3/sg_get_disk_io_stats_diff.3
/usr/share/man/man3/sg_get_disk_io_stats_diff_between.3
/usr/share/man/man3/sg_get_disk_io_stats_r.3
/usr/share/man/man3/sg_get_error.3
/usr/share/man/man3/sg_get_error_arg.3
/usr/share/man/man3/sg_get_error_details.3
/usr/share/man/man3/sg_get_error_errno.3
/usr/share/man/man3/sg_get_fs_stats.3
/usr/share/man/man3/sg_get_fs_stats_diff.3
/usr/share/man/man3/sg_get_fs_stats_diff_between.3
/usr/share/man/man3/sg_get_fs_stats_r.3
/usr/share/man/man3/sg_get_host_info.3
/usr/share/man/man3/sg_get_host_info_r.3
/usr/share/man/man3/sg_get_load_stats.3
/usr/share/man/man3/sg_get_load_stats_r.3
/usr/share/man/man3/sg_get_mem_stats.3
/usr/share/man/man3/sg_get_mem_stats_r.3
/usr/share/man/man3/sg_get_nelements.3
/usr/share/man/man3/sg_get_network_iface_stats.3
/usr/share/man/man3/sg_get_network_iface_stats_r.3
/usr/share/man/man3/sg_get_network_io_stats.3
/usr/share/man/man3/sg_get_network_io_stats_diff.3
/usr/share/man/man3/sg_get_network_io_stats_diff_between.3
/usr/share/man/man3/sg_get_network_io_stats_r.3
/usr/share/man/man3/sg_get_page_stats.3
/usr/share/man/man3/sg_get_page_stats_diff.3
/usr/share/man/man3/sg_get_page_stats_diff_between.3
/usr/share/man/man3/sg_get_page_stats_r.3
/usr/share/man/man3/sg_get_process_count.3
/usr/share/man/man3/sg_get_process_count_of.3
/usr/share/man/man3/sg_get_process_count_r.3
/usr/share/man/man3/sg_get_process_stats.3
/usr/share/man/man3/sg_get_process_stats_r.3
/usr/share/man/man3/sg_get_swap_stats.3
/usr/share/man/man3/sg_get_swap_stats_r.3
/usr/share/man/man3/sg_get_user_stats.3
/usr/share/man/man3/sg_get_user_stats_r.3
/usr/share/man/man3/sg_get_valid_filesystems.3
/usr/share/man/man3/sg_global_lock.3
/usr/share/man/man3/sg_global_unlock.3
/usr/share/man/man3/sg_init.3
/usr/share/man/man3/sg_internal-intro.3
/usr/share/man/man3/sg_intro.3
/usr/share/man/man3/sg_lock_mutex.3
/usr/share/man/man3/sg_network_iface_compare_name.3
/usr/share/man/man3/sg_network_io_compare_name.3
/usr/share/man/man3/sg_process_compare_cpu.3
/usr/share/man/man3/sg_process_compare_gid.3
/usr/share/man/man3/sg_process_compare_name.3
/usr/share/man/man3/sg_process_compare_pid.3
/usr/share/man/man3/sg_process_compare_res.3
/usr/share/man/man3/sg_process_compare_size.3
/usr/share/man/man3/sg_process_compare_time.3
/usr/share/man/man3/sg_process_compare_uid.3
/usr/share/man/man3/sg_prove_vector.3
/usr/share/man/man3/sg_set_error.3
/usr/share/man/man3/sg_set_error_with_errno.3
/usr/share/man/man3/sg_set_error_with_errno_code.3
/usr/share/man/man3/sg_set_valid_filesystems.3
/usr/share/man/man3/sg_shutdown.3
/usr/share/man/man3/sg_snapshot.3
/usr/share/man/man3/sg_str_error.3
/usr/share/man/man3/sg_strperror.3
/usr/share/man/man3/sg_unlock_mutex.3
/usr/share/man/man3/sg_vector_clear.3
/usr/share/man/man3/sg_vector_clone.3
/usr/share/man/man3/sg_vector_clone_into.3
/usr/share/man/man3/sg_vector_compute_diff.3
/usr/share/man/man3/sg_vector_create.3
/usr/share/man/man3/sg_vector_free.3
/usr/share/man/man3/sg_vector_resize.3
/usr/share/man/man3/statgrab.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libstatgrab/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libstatgrab.so.10
/usr/lib64/libstatgrab.so.10.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libstatgrab/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libstatgrab/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/statgrab-make-mrtg-config.1
/usr/share/man/man1/statgrab-make-mrtg-index.1
/usr/share/man/man1/statgrab.1
